# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=b'')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('symptom', models.TextField(blank=True, max_length=300, null=True)),
                ('treatment', models.TextField(blank=True, max_length=5000)),
                ('illustrations', models.ManyToManyField(blank=True, null=True, to='bio.Image')),
            ],
            options={
                'verbose_name': 'pathology',
                'verbose_name_plural': 'pathologies',
            },
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('symptom', models.TextField(blank=True, max_length=300, null=True)),
                ('treatment', models.TextField(blank=True, max_length=5000)),
                ('illustrations', models.ManyToManyField(blank=True, null=True, to='bio.Image')),
            ],
            options={
                'verbose_name': 'pest',
                'verbose_name_plural': 'pests',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('planting_description', models.TextField(blank=True, null=True)),
                ('planting_start', models.DateField(blank=True, null=True)),
                ('planting_end', models.DateField(blank=True, null=True)),
                ('harvest_description', models.TextField(blank=True, null=True)),
                ('harvest_start', models.DateField(blank=True, null=True)),
                ('harvest_end', models.DateField(blank=True, null=True)),
                ('temp_min', models.SmallIntegerField(blank=True, null=True)),
                ('temp_max', models.SmallIntegerField(blank=True, null=True)),
                ('humidity_min', models.SmallIntegerField(blank=True, null=True)),
                ('humidity_max', models.SmallIntegerField(blank=True, null=True)),
                ('heliophilous', models.NullBooleanField()),
                ('food', models.BooleanField()),
                ('toxic', models.BooleanField()),
                ('dislike', models.ManyToManyField(blank=True, null=True, related_name='_plant_dislike_+', to='bio.Plant')),
                ('images', models.ManyToManyField(blank=True, null=True, to='bio.Image')),
                ('like', models.ManyToManyField(blank=True, null=True, related_name='_plant_like_+', to='bio.Plant')),
                ('pathologies', models.ManyToManyField(blank=True, null=True, to='bio.Pathology')),
                ('pests', models.ManyToManyField(blank=True, null=True, to='bio.Pest')),
            ],
            options={
                'verbose_name': 'plant',
                'verbose_name_plural': 'plants',
            },
        ),
    ]
